### ISSUE TITLE
Github server error 502 during `Get Release handler`

### ISSUE THREAD

**Issue by beyarkay** [pyTooling/Actions#53]
I'm getting an error ([link](https://github.com/beyarkay/eskom-calendar/runs/7370578505?check_suite_focus=true#step:7:396)) that I can't figure out:
```
...
· Check SemVer compliance of the reference/tag
· Get GitHub API handler (authenticate)
· Get Repository handler
· Get Release handler
Traceback (most recent call last):                                 <---- error starts here
· RM set. All previous assets are being cleared...
  File "/releaser.py", line 179, in <module>
 - eastern-cape-graaf-reinet.ics
    asset.delete_asset()
  File "/usr/local/lib/python3.9/site-packages/github/GitReleaseAsset.py", line 138, in delete_asset
    headers, data = self._requester.requestJsonAndCheck("DELETE", self.url)
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {"message": "Server Error"}
```

[My workflow](https://github.com/beyarkay/eskom-calendar/blob/main/.github/workflows/manually_build_calendars.yaml#L30-L36) looks like:
```yaml
      uses: pyTooling/Actions/releaser@main
      with:
        tag: latest
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: calendars/*.*
```

Not sure what the issue here is, or if it's even a permanent one? (as opposed to github just being broken?)

Here's the link to the release in question that I was trying to update: https://github.com/beyarkay/eskom-calendar/releases/tag/latest.
The asset in question (`eastern-cape-graaf-reinet.ics`) doesn't exist in the release but I think it does exist in the new list of assets to be uploaded, maybe that's the issue?

**Comment by Paebbels** [comment]
Is this maybe related to the following issues?
* #48 
* #49 

-----
Sorry I'm not into JavaScript, so I can help here.  
@umarcor has currently not enough time to help fixing it.

So we're seeking for a skilled person helping out on that topic. It gets more and more reported.

**Comment by beyarkay** [comment]
Hmm they look similar, although not exactly the same. I'm going to retry manually and see if it goes away. My javascript isn't great either, but I'll have a look to see if I can implement something simple.

**Comment by umarcor** [comment]
The releaser Action is written in python, not in javascript! See https://github.com/pyTooling/Actions/blob/main/releaser/releaser.py.

It seems that the issue is produced in https://github.com/pyTooling/Actions/blob/31f02bb75bbad3920b001d1651d2adb8e0686397/releaser/releaser.py#L175-L179. Hence, I would suggest changing the title of this issue.

@beyarkay is this issue still reproducible? It might have been a transitory connection problem on GitHub.

**Comment by Paebbels** [comment]
I'm open to accept pull requests.

Please also see #82.

**Comment by Paebbels** [comment]
The repository offers now a new method of creating releases. This method deletes the old release and creates a new release to ensure a correct date.
